apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: "nmap-ssh-howto"
spec:
  scanType: "nmap"
  parameters:
    # Service Detection enabled
    - "-sV"
    # We'll just scan for port 22 to speed up the scan.
    - "-p"
    - "22"
    # Watch out to configure you network correctly and if you are allowed to perform scans against the hosts in it!
    - "10.96.221.147/24"
  cascades:
    matchLabels:
      securecodebox.io/intensive: high
      securecodebox.io/invasive: invasive


# Running the scan with "kubectl apply -f nmap-scan-cdr.yaml" 
# Track it with "kubectl get scans" 
# Scan overview with "kubectl describe scan nmap-scanme.nmap.org"